#? Config file for btop v. 1.3.0
# https://github.com/fdw/dotfiles/blob/main/btop.conf

#* Update time in milliseconds, recommended 2000 ms or above for better sample times for graphs.
update_ms = 500
