# French Accents

matches:
  - trigger: ":e'"
    replace: "é"

  - trigger: ":e`"
    replace: "è"

  - trigger: ":e^"
    replace: "ê"

  - trigger: ":e:"
    replace: "ë"

  - trigger: ":o^"
    replace: "ô"

  - trigger: ":a`"
    replace: "à"

  - trigger: ":a^"
    replace: "â"

  - trigger: ":i^"
    replace: "î"

  - trigger: ":i:"
    replace: "ï"

  - trigger: ":u`"
    replace: "ù"

  - trigger: ":u^"
    replace: "û"

  - trigger: ":c,"
    replace: "ç"

  - trigger: ":E'"
    replace: "É"

  - trigger: ":E`"
    replace: "È"

  - trigger: ":E^"
    replace: "Ê"

  - trigger: ":E:"
    replace: "Ë"

  - trigger: ":O^"
    replace: "Ô"

  - trigger: ":A`"
    replace: "À"

  - trigger: ":A^"
    replace: "Â"

  - trigger: ":I^"
    replace: "Î"

  - trigger: ":I:"
    replace: "Ï"

  - trigger: ":U`"
    replace: "Ù"

  - trigger: ":U^"
    replace: "Û"

  - trigger: ":C,"
    replace: "Ç"
